CREATE TABLE USUARIOS (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  DOCUMENTO TEXT NOT NULL,
  NOMBRE_RAZON_SOCIAL TEXT NULL,
  APELLIDOS TEXT NULL,
  TELEFONO TEXT NULL,
  CORREO TEXT NULL,
  ROL TEXT NULL,
  USERNAME TEXT NULL,
  PASS TEXT NULL,
  TIPO_DOC INT NULL,
  AVATAR TEXT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE CATEGORIAS (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE TEXT NULL,
  DESCRIPCION TEXT NULL,
  ESTADO TEXT NULL,
  F_CREACION DATE NULL,
  F_MOD DATE NULL,
  COD_PADRE INTEGER UNSIGNED NULL,
  IMAGEN TEXT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE PRODUCTO (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  CATEGORIAS_ID INTEGER UNSIGNED NOT NULL,
  REFERENCIA TEXT NULL,
  NOMBRE TEXT NULL,
  IMAGEN TEXT NULL,
  PRECIO FLOAT UNSIGNED NULL,
  STOCK INTEGER UNSIGNED NULL,
  ESTADO TEXT NULL,
  F_CREACION DATE NULL,
  F_MOD DATE NULL,
  PROCESADOR TEXT NULL,
  MARCA_PROCESADOR TEXT NULL,
  GENERACION_SERIE TEXT NULL,
  RAM TEXT NULL,
  TIPO_RAM TEXT NULL,
  STORAGE TEXT NULL,
  TIPO_STORAGE TEXT NULL,
  PANTALLA TEXT NULL,
  TIPO_PANTALLA TEXT NULL,
  TAMANO_PANTALLA TEXT NULL,
  BATERIA TEXT NULL,
  CAMARA TEXT NULL,
  FUNCIONALIDAD TEXT NULL,
  CONEXION TEXT NULL,
  SISTEMA TEXT NULL,
  SO TEXT NULL,
  SEGMENTO TEXT NULL,
  FRECUENCIA TEXT NULL,
  MATERIAL TEXT NULL,
  COLOR TEXT NULL,
  PESO FLOAT UNSIGNED NULL,
  LARGO FLOAT UNSIGNED NULL,
  ANCHO FLOAT UNSIGNED NULL,
  ALTO FLOAT UNSIGNED NULL,
  DISTRIBUCION TEXT NULL,
  IDIOMA TEXT NULL,
  RESOLUCION TEXT NULL,
  DESCRIPCION TEXT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(CATEGORIAS_ID)
    REFERENCES CATEGORIAS(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE PQR (
  USUARIOS_ID INTEGER UNSIGNED NOT NULL,
  DESCRIPCION TEXT NULL,
  FECHA DATE NULL,
  ESTADO TEXT NULL,
  RESPUESTA TEXT NULL,
  FOREIGN KEY(USUARIOS_ID)
    REFERENCES USUARIOS(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE DETAL_PEDIDO (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PRODUCTO_ID INTEGER UNSIGNED NOT NULL,
  CANTIDAD INTEGER UNSIGNED NULL,
  PRECIO FLOAT NULL,
  PRECIO_T FLOAT NULL,
  PRIMARY KEY(ID),
  INDEX DETAL_PEDIDO_FKIndex1(PRODUCTO_ID),
  FOREIGN KEY(PRODUCTO_ID)
    REFERENCES PRODUCTO(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE DIRECCIONES (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  USUARIOS_ID INTEGER UNSIGNED NOT NULL,
  DIRECCION TEXT NULL,
  CIUDAD TEXT NULL,
  DEPARTAMENTO TEXT NULL,
  TELEFONO TEXT NULL,
  OBSERVACION TEXT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(USUARIOS_ID)
    REFERENCES USUARIOS(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE PRECIO_OFERTA (
  USUARIOS_ID INTEGER UNSIGNED NOT NULL,
  PRODUCTO_ID INTEGER UNSIGNED NOT NULL,
  PRECIO FLOAT NULL,
  OBSERVACION TEXT NULL,
  F_VENCIMIENTO DATE NULL,
  PRIMARY KEY(USUARIOS_ID, PRODUCTO_ID),
  INDEX PRECIO_OFERTA_FKIndex1(PRODUCTO_ID),
  FOREIGN KEY(USUARIOS_ID)
    REFERENCES USUARIOS(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PRODUCTO_ID)
    REFERENCES PRODUCTO(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE COTIZACIONES (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  DETAL_PEDIDO_ID INTEGER UNSIGNED NOT NULL,
  USUARIOS_ID INTEGER UNSIGNED NOT NULL,
  OBSERVACION TEXT NULL,
  F_CREACION DATE NULL,
  ESTADO INT NULL,
  TIPO_OC INT NULL,
  F_VENCIMIENTO DATE NULL,
  FLETE FLOAT NULL,
  TOTAL FLOAT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(USUARIOS_ID)
    REFERENCES USUARIOS(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(DETAL_PEDIDO_ID)
    REFERENCES DETAL_PEDIDO(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE HISTORIAL_CLIENTE ( 
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  USUARIOS_ID INTEGER UNSIGNED NOT NULL,
  PRODUCTO_ID INTEGER UNSIGNED NOT NULL,
  COMPRA INTEGER UNSIGNED NULL,
  VISTA INTEGER UNSIGNED NULL,
  PRECIO INTEGER UNSIGNED NULL,
  FECHA DATE NULL,
  UNIDADES INTEGER UNSIGNED NULL,
  PRIMARY KEY(ID),
  INDEX HISTORIAL_CLIENTE_FKIndex1(PRODUCTO_ID),
  FOREIGN KEY(USUARIOS_ID)
    REFERENCES USUARIOS(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PRODUCTO_ID)
    REFERENCES PRODUCTO(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE PEDIDO (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  DIRECCIONES_ID INTEGER UNSIGNED NOT NULL,
  COTIZACIONES_ID INTEGER UNSIGNED NOT NULL,
  OBSERVACION TEXT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(COTIZACIONES_ID)
    REFERENCES COTIZACIONES(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(DIRECCIONES_ID)
    REFERENCES DIRECCIONES(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);